name = "bzn-develop-bot"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
workers_dev = true

[observability.logs]
enabled = true

# KV Namespaces для хранения данных
[[kv_namespaces]]
binding = "BZN_BOT_KV"
id = "842f885ab9c24cd3b56c3b1a257b106d"
preview_id = "2ae00ebc23b14aee8bd48c3c7d4b69c4"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "bzn-bot-db"
database_id = "86c3bdb3-bdae-417b-bb60-c1d7d8a54f79"

# Environment variables (secrets should be set via wrangler secret)
[vars]
# BOT_TOKEN, ADMIN_CHAT_ID, TRANSCRIPTION_API_TOKEN will be set as secrets
NODE_ENV = "production"
LOCALE = "ru"

# Build configuration (не нужна для TypeScript воркеров)
# [build]
# command = "npm run build:worker"

# Cron triggers для проверки отложенных сообщений
[triggers]
crons = ["* * * * *"]  # Каждую минуту

# Development configuration
[env.development]
name = "bzn-bot-worker-dev"

[env.production]
name = "bzn-bot-worker"
