
export const GOOGLE_FONT = 'google';
export const SYSTEM_FONT = 'system';
// <editor-fold desc="Fonts List" defaultstate="collapsed">


export const altrpFontsSet =
  {

    // System fonts.
    'Arial': SYSTEM_FONT,
    'Tahoma': SYSTEM_FONT,
    'Verdana': SYSTEM_FONT,
    'Helvetica': SYSTEM_FONT,
    'Times New Roman': SYSTEM_FONT,
    'Trebuchet MS': SYSTEM_FONT,
    'Georgia': SYSTEM_FONT,

    // Google Fonts (last update: 12/07/2020).
    'ABeeZee': GOOGLE_FONT,
    'Abel': GOOGLE_FONT,
    'Abhaya Libre': GOOGLE_FONT,
    'Abril Fatface': GOOGLE_FONT,
    'Aclonica': GOOGLE_FONT,
    'Acme': GOOGLE_FONT,
    'Actor': GOOGLE_FONT,
    'Adamina': GOOGLE_FONT,
    'Advent Pro': GOOGLE_FONT,
    'Aguafina Script': GOOGLE_FONT,
    'Akronim': GOOGLE_FONT,
    'Aladin': GOOGLE_FONT,
    'Alata': GOOGLE_FONT,
    'Alatsi': GOOGLE_FONT,
    'Aldrich': GOOGLE_FONT,
    'Alef': GOOGLE_FONT,
    'Alegreya': GOOGLE_FONT,
    'Alegreya SC': GOOGLE_FONT,
    'Alegreya Sans': GOOGLE_FONT,
    'Alegreya Sans SC': GOOGLE_FONT,
    'Aleo': GOOGLE_FONT,
    'Alex Brush': GOOGLE_FONT,
    'Alfa Slab One': GOOGLE_FONT,
    'Alice': GOOGLE_FONT,
    'Alike': GOOGLE_FONT,
    'Alike Angular': GOOGLE_FONT,
    'Allan': GOOGLE_FONT,
    'Allerta': GOOGLE_FONT,
    'Allerta Stencil': GOOGLE_FONT,
    'Allura': GOOGLE_FONT,
    'Almarai': GOOGLE_FONT,
    'Almendra': GOOGLE_FONT,
    'Almendra Display': GOOGLE_FONT,
    'Almendra SC': GOOGLE_FONT,
    'Amarante': GOOGLE_FONT,
    'Amaranth': GOOGLE_FONT,
    'Amatic SC': GOOGLE_FONT,
    'Amethysta': GOOGLE_FONT,
    'Amiko': GOOGLE_FONT,
    'Amiri': GOOGLE_FONT,
    'Amita': GOOGLE_FONT,
    'Anaheim': GOOGLE_FONT,
    'Andada': GOOGLE_FONT,
    'Andika': GOOGLE_FONT,
    'Angkor': GOOGLE_FONT,
    'Annie Use Your Telescope': GOOGLE_FONT,
    'Anonymous Pro': GOOGLE_FONT,
    'Antic': GOOGLE_FONT,
    'Antic Didone': GOOGLE_FONT,
    'Antic Slab': GOOGLE_FONT,
    'Anton': GOOGLE_FONT,
    'Arapey': GOOGLE_FONT,
    'Arbutus': GOOGLE_FONT,
    'Arbutus Slab': GOOGLE_FONT,
    'Architects Daughter': GOOGLE_FONT,
    'Archivo': GOOGLE_FONT,
    'Archivo Black': GOOGLE_FONT,
    'Archivo Narrow': GOOGLE_FONT,
    'Aref Ruqaa': GOOGLE_FONT,
    'Arima Madurai': GOOGLE_FONT,
    'Arimo': GOOGLE_FONT,
    'Arizonia': GOOGLE_FONT,
    'Armata': GOOGLE_FONT,
    'Arsenal': GOOGLE_FONT,
    'Artifika': GOOGLE_FONT,
    'Arvo': GOOGLE_FONT,
    'Arya': GOOGLE_FONT,
    'Asap': GOOGLE_FONT,
    'Asap Condensed': GOOGLE_FONT,
    'Asar': GOOGLE_FONT,
    'Asset': GOOGLE_FONT,
    'Assistant': GOOGLE_FONT,
    'Astloch': GOOGLE_FONT,
    'Asul': GOOGLE_FONT,
    'Athiti': GOOGLE_FONT,
    'Atma': GOOGLE_FONT,
    'Atomic Age': GOOGLE_FONT,
    'Aubrey': GOOGLE_FONT,
    'Audiowide': GOOGLE_FONT,
    'Autour One': GOOGLE_FONT,
    'Average': GOOGLE_FONT,
    'Average Sans': GOOGLE_FONT,
    'Averia Gruesa Libre': GOOGLE_FONT,
    'Averia Libre': GOOGLE_FONT,
    'Averia Sans Libre': GOOGLE_FONT,
    'Averia Serif Libre': GOOGLE_FONT,
    'B612': GOOGLE_FONT,
    'B612 Mono': GOOGLE_FONT,
    'Bad Script': GOOGLE_FONT,
    'Bahiana': GOOGLE_FONT,
    'Bahianita': GOOGLE_FONT,
    'Bai Jamjuree': GOOGLE_FONT,
    'Baloo 2': GOOGLE_FONT,
    'Baloo Bhai 2': GOOGLE_FONT,
    'Baloo Bhaina 2': GOOGLE_FONT,
    'Baloo Chettan 2': GOOGLE_FONT,
    'Baloo Da 2': GOOGLE_FONT,
    'Baloo Paaji 2': GOOGLE_FONT,
    'Baloo Tamma 2': GOOGLE_FONT,
    'Baloo Tammudu 2': GOOGLE_FONT,
    'Baloo Thambi 2': GOOGLE_FONT,
    'Balsamiq Sans': GOOGLE_FONT,
    'Balthazar': GOOGLE_FONT,
    'Bangers': GOOGLE_FONT,
    'Barlow': GOOGLE_FONT,
    'Barlow Condensed': GOOGLE_FONT,
    'Barlow Semi Condensed': GOOGLE_FONT,
    'Barriecito': GOOGLE_FONT,
    'Barrio': GOOGLE_FONT,
    'Basic': GOOGLE_FONT,
    'Baskervville': GOOGLE_FONT,
    'Battambang': GOOGLE_FONT,
    'Baumans': GOOGLE_FONT,
    'Bayon': GOOGLE_FONT,
    'Be Vietnam': GOOGLE_FONT,
    'Bebas Neue': GOOGLE_FONT,
    'Belgrano': GOOGLE_FONT,
    'Bellefair': GOOGLE_FONT,
    'Belleza': GOOGLE_FONT,
    'Bellota': GOOGLE_FONT,
    'Bellota Text': GOOGLE_FONT,
    'BenchNine': GOOGLE_FONT,
    'Bentham': GOOGLE_FONT,
    'Berkshire Swash': GOOGLE_FONT,
    'Beth Ellen': GOOGLE_FONT,
    'Bevan': GOOGLE_FONT,
    'Big Shoulders Display': GOOGLE_FONT,
    'Big Shoulders Text': GOOGLE_FONT,
    'Bigelow Rules': GOOGLE_FONT,
    'Bigshot One': GOOGLE_FONT,
    'Bilbo': GOOGLE_FONT,
    'Bilbo Swash Caps': GOOGLE_FONT,
    'BioRhyme': GOOGLE_FONT,
    'BioRhyme Expanded': GOOGLE_FONT,
    'Biryani': GOOGLE_FONT,
    'Bitter': GOOGLE_FONT,
    'Black And White Picture': GOOGLE_FONT,
    'Black Han Sans': GOOGLE_FONT,
    'Black Ops One': GOOGLE_FONT,
    'Blinker': GOOGLE_FONT,
    'Bokor': GOOGLE_FONT,
    'Bonbon': GOOGLE_FONT,
    'Boogaloo': GOOGLE_FONT,
    'Bowlby One': GOOGLE_FONT,
    'Bowlby One SC': GOOGLE_FONT,
    'Brawler': GOOGLE_FONT,
    'Bree Serif': GOOGLE_FONT,
    'Bubblegum Sans': GOOGLE_FONT,
    'Bubbler One': GOOGLE_FONT,
    'Buda': GOOGLE_FONT,
    'Buenard': GOOGLE_FONT,
    'Bungee': GOOGLE_FONT,
    'Bungee Hairline': GOOGLE_FONT,
    'Bungee Inline': GOOGLE_FONT,
    'Bungee Outline': GOOGLE_FONT,
    'Bungee Shade': GOOGLE_FONT,
    'Butcherman': GOOGLE_FONT,
    'Butterfly Kids': GOOGLE_FONT,
    'Cabin': GOOGLE_FONT,
    'Cabin Condensed': GOOGLE_FONT,
    'Cabin Sketch': GOOGLE_FONT,
    'Caesar Dressing': GOOGLE_FONT,
    'Cagliostro': GOOGLE_FONT,
    'Cairo': GOOGLE_FONT,
    'Caladea': GOOGLE_FONT,
    'Calistoga': GOOGLE_FONT,
    'Calligraffitti': GOOGLE_FONT,
    'Cambay': GOOGLE_FONT,
    'Cambo': GOOGLE_FONT,
    'Candal': GOOGLE_FONT,
    'Cantarell': GOOGLE_FONT,
    'Cantata One': GOOGLE_FONT,
    'Cantora One': GOOGLE_FONT,
    'Capriola': GOOGLE_FONT,
    'Cardo': GOOGLE_FONT,
    'Carme': GOOGLE_FONT,
    'Carrois Gothic': GOOGLE_FONT,
    'Carrois Gothic SC': GOOGLE_FONT,
    'Carter One': GOOGLE_FONT,
    'Catamaran': GOOGLE_FONT,
    'Caudex': GOOGLE_FONT,
    'Caveat': GOOGLE_FONT,
    'Caveat Brush': GOOGLE_FONT,
    'Cedarville Cursive': GOOGLE_FONT,
    'Ceviche One': GOOGLE_FONT,
    'Chakra Petch': GOOGLE_FONT,
    'Changa': GOOGLE_FONT,
    'Changa One': GOOGLE_FONT,
    'Chango': GOOGLE_FONT,
    'Charm': GOOGLE_FONT,
    'Charmonman': GOOGLE_FONT,
    'Chathura': GOOGLE_FONT,
    'Chau Philomene One': GOOGLE_FONT,
    'Chela One': GOOGLE_FONT,
    'Chelsea Market': GOOGLE_FONT,
    'Chenla': GOOGLE_FONT,
    'Cherry Cream Soda': GOOGLE_FONT,
    'Cherry Swash': GOOGLE_FONT,
    'Chewy': GOOGLE_FONT,
    'Chicle': GOOGLE_FONT,
    'Chilanka': GOOGLE_FONT,
    'Chivo': GOOGLE_FONT,
    'Chonburi': GOOGLE_FONT,
    'Cinzel': GOOGLE_FONT,
    'Cinzel Decorative': GOOGLE_FONT,
    'Clicker Script': GOOGLE_FONT,
    'Coda': GOOGLE_FONT,
    'Coda Caption': GOOGLE_FONT,
    'Codystar': GOOGLE_FONT,
    'Coiny': GOOGLE_FONT,
    'Combo': GOOGLE_FONT,
    'Comfortaa': GOOGLE_FONT,
    'Comic Neue': GOOGLE_FONT,
    'Coming Soon': GOOGLE_FONT,
    'Concert One': GOOGLE_FONT,
    'Condiment': GOOGLE_FONT,
    'Content': GOOGLE_FONT,
    'Contrail One': GOOGLE_FONT,
    'Convergence': GOOGLE_FONT,
    'Cookie': GOOGLE_FONT,
    'Copse': GOOGLE_FONT,
    'Corben': GOOGLE_FONT,
    'Cormorant': GOOGLE_FONT,
    'Cormorant Garamond': GOOGLE_FONT,
    'Cormorant Infant': GOOGLE_FONT,
    'Cormorant SC': GOOGLE_FONT,
    'Cormorant Unicase': GOOGLE_FONT,
    'Cormorant Upright': GOOGLE_FONT,
    'Courgette': GOOGLE_FONT,
    'Courier Prime': GOOGLE_FONT,
    'Cousine': GOOGLE_FONT,
    'Coustard': GOOGLE_FONT,
    'Covered By Your Grace': GOOGLE_FONT,
    'Crafty Girls': GOOGLE_FONT,
    'Creepster': GOOGLE_FONT,
    'Crete Round': GOOGLE_FONT,
    'Crimson Pro': GOOGLE_FONT,
    'Crimson Text': GOOGLE_FONT,
    'Croissant One': GOOGLE_FONT,
    'Crushed': GOOGLE_FONT,
    'Cuprum': GOOGLE_FONT,
    'Cute Font': GOOGLE_FONT,
    'Cutive': GOOGLE_FONT,
    'Cutive Mono': GOOGLE_FONT,
    'DM Mono': GOOGLE_FONT,
    'DM Sans': GOOGLE_FONT,
    'DM Serif Display': GOOGLE_FONT,
    'DM Serif Text': GOOGLE_FONT,
    'Damion': GOOGLE_FONT,
    'Dancing Script': GOOGLE_FONT,
    'Dangrek': GOOGLE_FONT,
    'Darker Grotesque': GOOGLE_FONT,
    'David Libre': GOOGLE_FONT,
    'Dawning of a New Day': GOOGLE_FONT,
    'Days One': GOOGLE_FONT,
    'Dekko': GOOGLE_FONT,
    'Delius': GOOGLE_FONT,
    'Delius Swash Caps': GOOGLE_FONT,
    'Delius Unicase': GOOGLE_FONT,
    'Della Respira': GOOGLE_FONT,
    'Denk One': GOOGLE_FONT,
    'Devonshire': GOOGLE_FONT,
    'Dhurjati': GOOGLE_FONT,
    'Didact Gothic': GOOGLE_FONT,
    'Diplomata': GOOGLE_FONT,
    'Diplomata SC': GOOGLE_FONT,
    'Do Hyeon': GOOGLE_FONT,
    'Dokdo': GOOGLE_FONT,
    'Domine': GOOGLE_FONT,
    'Donegal One': GOOGLE_FONT,
    'Doppio One': GOOGLE_FONT,
    'Dorsa': GOOGLE_FONT,
    'Dosis': GOOGLE_FONT,
    'Dr Sugiyama': GOOGLE_FONT,
    'Duru Sans': GOOGLE_FONT,
    'Dynalight': GOOGLE_FONT,
    'EB Garamond': GOOGLE_FONT,
    'Eagle Lake': GOOGLE_FONT,
    'East Sea Dokdo': GOOGLE_FONT,
    'Eater': GOOGLE_FONT,
    'Economica': GOOGLE_FONT,
    'Eczar': GOOGLE_FONT,
    'El Messiri': GOOGLE_FONT,
    'Electrolize': GOOGLE_FONT,
    'Elsie': GOOGLE_FONT,
    'Elsie Swash Caps': GOOGLE_FONT,
    'Emblema One': GOOGLE_FONT,
    'Emilys Candy': GOOGLE_FONT,
    'Encode Sans': GOOGLE_FONT,
    'Encode Sans Condensed': GOOGLE_FONT,
    'Encode Sans Expanded': GOOGLE_FONT,
    'Encode Sans Semi Condensed': GOOGLE_FONT,
    'Encode Sans Semi Expanded': GOOGLE_FONT,
    'Engagement': GOOGLE_FONT,
    'Englebert': GOOGLE_FONT,
    'Enriqueta': GOOGLE_FONT,
    'Erica One': GOOGLE_FONT,
    'Esteban': GOOGLE_FONT,
    'Euphoria Script': GOOGLE_FONT,
    'Ewert': GOOGLE_FONT,
    'Exo': GOOGLE_FONT,
    'Exo 2': GOOGLE_FONT,
    'Expletus Sans': GOOGLE_FONT,
    'Fahkwang': GOOGLE_FONT,
    'Fanwood Text': GOOGLE_FONT,
    'Farro': GOOGLE_FONT,
    'Farsan': GOOGLE_FONT,
    'Fascinate': GOOGLE_FONT,
    'Fascinate Inline': GOOGLE_FONT,
    'Faster One': GOOGLE_FONT,
    'Fasthand': GOOGLE_FONT,
    'Fauna One': GOOGLE_FONT,
    'Faustina': GOOGLE_FONT,
    'Federant': GOOGLE_FONT,
    'Federo': GOOGLE_FONT,
    'Felipa': GOOGLE_FONT,
    'Fenix': GOOGLE_FONT,
    'Finger Paint': GOOGLE_FONT,
    'Fira Code': GOOGLE_FONT,
    'Fira Mono': GOOGLE_FONT,
    'Fira Sans': GOOGLE_FONT,
    'Fira Sans Condensed': GOOGLE_FONT,
    'Fira Sans Extra Condensed': GOOGLE_FONT,
    'Fjalla One': GOOGLE_FONT,
    'Fjord One': GOOGLE_FONT,
    'Flamenco': GOOGLE_FONT,
    'Flavors': GOOGLE_FONT,
    'Fondamento': GOOGLE_FONT,
    'Fontdiner Swanky': GOOGLE_FONT,
    'Forum': GOOGLE_FONT,
    'Francois One': GOOGLE_FONT,
    'Fraunces': GOOGLE_FONT,
    'Frank Ruhl Libre': GOOGLE_FONT,
    'Freckle Face': GOOGLE_FONT,
    'Fredericka the Great': GOOGLE_FONT,
    'Fredoka One': GOOGLE_FONT,
    'Freehand': GOOGLE_FONT,
    'Fresca': GOOGLE_FONT,
    'Frijole': GOOGLE_FONT,
    'Fruktur': GOOGLE_FONT,
    'Fugaz One': GOOGLE_FONT,
    'GFS Didot': GOOGLE_FONT,
    'GFS Neohellenic': GOOGLE_FONT,
    'Gabriela': GOOGLE_FONT,
    'Gaegu': GOOGLE_FONT,
    'Gafata': GOOGLE_FONT,
    'Galada': GOOGLE_FONT,
    'Galdeano': GOOGLE_FONT,
    'Galindo': GOOGLE_FONT,
    'Gamja Flower': GOOGLE_FONT,
    'Gayathri': GOOGLE_FONT,
    'Gelasio': GOOGLE_FONT,
    'Gentium Basic': GOOGLE_FONT,
    'Gentium Book Basic': GOOGLE_FONT,
    'Geo': GOOGLE_FONT,
    'Geostar': GOOGLE_FONT,
    'Geostar Fill': GOOGLE_FONT,
    'Germania One': GOOGLE_FONT,
    'Gidugu': GOOGLE_FONT,
    'Gilda Display': GOOGLE_FONT,
    'Girassol': GOOGLE_FONT,
    'Give You Glory': GOOGLE_FONT,
    'Glass Antiqua': GOOGLE_FONT,
    'Glegoo': GOOGLE_FONT,
    'Gloria Hallelujah': GOOGLE_FONT,
    'Goblin One': GOOGLE_FONT,
    'Gochi Hand': GOOGLE_FONT,
    'Gorditas': GOOGLE_FONT,
    'Gothic A1': GOOGLE_FONT,
    'Gotu': GOOGLE_FONT,
    'Goudy Bookletter 1911': GOOGLE_FONT,
    'Graduate': GOOGLE_FONT,
    'Grand Hotel': GOOGLE_FONT,
    'Gravitas One': GOOGLE_FONT,
    'Great Vibes': GOOGLE_FONT,
    'Grenze': GOOGLE_FONT,
    'Grenze Gotisch': GOOGLE_FONT,
    'Griffy': GOOGLE_FONT,
    'Gruppo': GOOGLE_FONT,
    'Gudea': GOOGLE_FONT,
    'Gugi': GOOGLE_FONT,
    'Gupter': GOOGLE_FONT,
    'Gurajada': GOOGLE_FONT,
    'Habibi': GOOGLE_FONT,
    'Halant': GOOGLE_FONT,
    'Hammersmith One': GOOGLE_FONT,
    'Hanalei': GOOGLE_FONT,
    'Hanalei Fill': GOOGLE_FONT,
    'Handlee': GOOGLE_FONT,
    'Hanuman': GOOGLE_FONT,
    'Happy Monkey': GOOGLE_FONT,
    'Harmattan': GOOGLE_FONT,
    'Headland One': GOOGLE_FONT,
    'Heebo': GOOGLE_FONT,
    'Henny Penny': GOOGLE_FONT,
    'Hepta Slab': GOOGLE_FONT,
    'Herr Von Muellerhoff': GOOGLE_FONT,
    'Hi Melody': GOOGLE_FONT,
    'Hind': GOOGLE_FONT,
    'Hind Guntur': GOOGLE_FONT,
    'Hind Madurai': GOOGLE_FONT,
    'Hind Siliguri': GOOGLE_FONT,
    'Hind Vadodara': GOOGLE_FONT,
    'Holtwood One SC': GOOGLE_FONT,
    'Homemade Apple': GOOGLE_FONT,
    'Homenaje': GOOGLE_FONT,
    'IBM Plex Mono': GOOGLE_FONT,
    'IBM Plex Sans': GOOGLE_FONT,
    'IBM Plex Sans Condensed': GOOGLE_FONT,
    'IBM Plex Serif': GOOGLE_FONT,
    'IM Fell DW Pica': GOOGLE_FONT,
    'IM Fell DW Pica SC': GOOGLE_FONT,
    'IM Fell Double Pica': GOOGLE_FONT,
    'IM Fell Double Pica SC': GOOGLE_FONT,
    'IM Fell English': GOOGLE_FONT,
    'IM Fell English SC': GOOGLE_FONT,
    'IM Fell French Canon': GOOGLE_FONT,
    'IM Fell French Canon SC': GOOGLE_FONT,
    'IM Fell Great Primer': GOOGLE_FONT,
    'IM Fell Great Primer SC': GOOGLE_FONT,
    'Ibarra Real Nova': GOOGLE_FONT,
    'Iceberg': GOOGLE_FONT,
    'Iceland': GOOGLE_FONT,
    'Imprima': GOOGLE_FONT,
    'Inconsolata': GOOGLE_FONT,
    'Inder': GOOGLE_FONT,
    'Indie Flower': GOOGLE_FONT,
    'Inika': GOOGLE_FONT,
    'Inknut Antiqua': GOOGLE_FONT,
    'Inria Sans': GOOGLE_FONT,
    'Inria Serif': GOOGLE_FONT,
    'Inter': GOOGLE_FONT,
    'Inter Tight': GOOGLE_FONT,
    'Irish Grover': GOOGLE_FONT,
    'Istok Web': GOOGLE_FONT,
    'Italiana': GOOGLE_FONT,
    'Italianno': GOOGLE_FONT,
    'Itim': GOOGLE_FONT,
    'Jacques Francois': GOOGLE_FONT,
    'Jacques Francois Shadow': GOOGLE_FONT,
    'Jaldi': GOOGLE_FONT,
    'Jim Nightshade': GOOGLE_FONT,
    'Jockey One': GOOGLE_FONT,
    'Jolly Lodger': GOOGLE_FONT,
    'Jomhuria': GOOGLE_FONT,
    'Jomolhari': GOOGLE_FONT,
    'Josefin Sans': GOOGLE_FONT,
    'Josefin Slab': GOOGLE_FONT,
    'Jost': GOOGLE_FONT,
    'Joti One': GOOGLE_FONT,
    'Jua': GOOGLE_FONT,
    'Judson': GOOGLE_FONT,
    'Julee': GOOGLE_FONT,
    'Julius Sans One': GOOGLE_FONT,
    'Junge': GOOGLE_FONT,
    'Jura': GOOGLE_FONT,
    'Just Another Hand': GOOGLE_FONT,
    'Just Me Again Down Here': GOOGLE_FONT,
    'K2D': GOOGLE_FONT,
    'Kadwa': GOOGLE_FONT,
    'Kalam': GOOGLE_FONT,
    'Kameron': GOOGLE_FONT,
    'Kanit': GOOGLE_FONT,
    'Kantumruy': GOOGLE_FONT,
    'Karla': GOOGLE_FONT,
    'Karma': GOOGLE_FONT,
    'Katibeh': GOOGLE_FONT,
    'Kaushan Script': GOOGLE_FONT,
    'Kavivanar': GOOGLE_FONT,
    'Kavoon': GOOGLE_FONT,
    'Kdam Thmor': GOOGLE_FONT,
    'Keania One': GOOGLE_FONT,
    'Kelly Slab': GOOGLE_FONT,
    'Kenia': GOOGLE_FONT,
    'Khand': GOOGLE_FONT,
    'Khmer': GOOGLE_FONT,
    'Khula': GOOGLE_FONT,
    'Kirang Haerang': GOOGLE_FONT,
    'Kite One': GOOGLE_FONT,
    'Knewave': GOOGLE_FONT,
    'KoHo': GOOGLE_FONT,
    'Kodchasan': GOOGLE_FONT,
    'Kosugi': GOOGLE_FONT,
    'Kosugi Maru': GOOGLE_FONT,
    'Kotta One': GOOGLE_FONT,
    'Koulen': GOOGLE_FONT,
    'Kranky': GOOGLE_FONT,
    'Kreon': GOOGLE_FONT,
    'Kristi': GOOGLE_FONT,
    'Krona One': GOOGLE_FONT,
    'Krub': GOOGLE_FONT,
    'Kulim Park': GOOGLE_FONT,
    'Kumar One': GOOGLE_FONT,
    'Kumar One Outline': GOOGLE_FONT,
    'Kurale': GOOGLE_FONT,
    'La Belle Aurore': GOOGLE_FONT,
    'Lacquer': GOOGLE_FONT,
    'Laila': GOOGLE_FONT,
    'Lakki Reddy': GOOGLE_FONT,
    'Lalezar': GOOGLE_FONT,
    'Lancelot': GOOGLE_FONT,
    'Lateef': GOOGLE_FONT,
    'Lato': GOOGLE_FONT,
    'League Script': GOOGLE_FONT,
    'Leckerli One': GOOGLE_FONT,
    'Ledger': GOOGLE_FONT,
    'Lekton': GOOGLE_FONT,
    'Lemon': GOOGLE_FONT,
    'Lemonada': GOOGLE_FONT,
    'Lexend Deca': GOOGLE_FONT,
    'Lexend Exa': GOOGLE_FONT,
    'Lexend Giga': GOOGLE_FONT,
    'Lexend Mega': GOOGLE_FONT,
    'Lexend Peta': GOOGLE_FONT,
    'Lexend Tera': GOOGLE_FONT,
    'Lexend Zetta': GOOGLE_FONT,
    'Libre Barcode 128': GOOGLE_FONT,
    'Libre Barcode 128 Text': GOOGLE_FONT,
    'Libre Barcode 39': GOOGLE_FONT,
    'Libre Barcode 39 Extended': GOOGLE_FONT,
    'Libre Barcode 39 Extended Text': GOOGLE_FONT,
    'Libre Barcode 39 Text': GOOGLE_FONT,
    'Libre Baskerville': GOOGLE_FONT,
    'Libre Caslon Display': GOOGLE_FONT,
    'Libre Caslon Text': GOOGLE_FONT,
    'Libre Franklin': GOOGLE_FONT,
    'Life Savers': GOOGLE_FONT,
    'Lilita One': GOOGLE_FONT,
    'Lily Script One': GOOGLE_FONT,
    'Limelight': GOOGLE_FONT,
    'Linden Hill': GOOGLE_FONT,
    'Literata': GOOGLE_FONT,
    'Liu Jian Mao Cao': GOOGLE_FONT,
    'Livvic': GOOGLE_FONT,
    'Lobster': GOOGLE_FONT,
    'Lobster Two': GOOGLE_FONT,
    'Londrina Outline': GOOGLE_FONT,
    'Londrina Shadow': GOOGLE_FONT,
    'Londrina Sketch': GOOGLE_FONT,
    'Londrina Solid': GOOGLE_FONT,
    'Long Cang': GOOGLE_FONT,
    'Lora': GOOGLE_FONT,
    'Love Ya Like A Sister': GOOGLE_FONT,
    'Loved by the King': GOOGLE_FONT,
    'Lovers Quarrel': GOOGLE_FONT,
    'Luckiest Guy': GOOGLE_FONT,
    'Lusitana': GOOGLE_FONT,
    'Lustria': GOOGLE_FONT,
    'M PLUS 1p': GOOGLE_FONT,
    'M PLUS Rounded 1c': GOOGLE_FONT,
    'Ma Shan Zheng': GOOGLE_FONT,
    'Macondo': GOOGLE_FONT,
    'Macondo Swash Caps': GOOGLE_FONT,
    'Mada': GOOGLE_FONT,
    'Magra': GOOGLE_FONT,
    'Maiden Orange': GOOGLE_FONT,
    'Maitree': GOOGLE_FONT,
    'Major Mono Display': GOOGLE_FONT,
    'Mako': GOOGLE_FONT,
    'Mali': GOOGLE_FONT,
    'Mallanna': GOOGLE_FONT,
    'Mandali': GOOGLE_FONT,
    'Manjari': GOOGLE_FONT,
    'Manrope': GOOGLE_FONT,
    'Mansalva': GOOGLE_FONT,
    'Manuale': GOOGLE_FONT,
    'Marcellus': GOOGLE_FONT,
    'Marcellus SC': GOOGLE_FONT,
    'Marck Script': GOOGLE_FONT,
    'Margarine': GOOGLE_FONT,
    'Markazi Text': GOOGLE_FONT,
    'Marko One': GOOGLE_FONT,
    'Marmelad': GOOGLE_FONT,
    'Martel': GOOGLE_FONT,
    'Martel Sans': GOOGLE_FONT,
    'Marvel': GOOGLE_FONT,
    'Mate': GOOGLE_FONT,
    'Mate SC': GOOGLE_FONT,
    'Maven Pro': GOOGLE_FONT,
    'McLaren': GOOGLE_FONT,
    'Meddon': GOOGLE_FONT,
    'MedievalSharp': GOOGLE_FONT,
    'Medula One': GOOGLE_FONT,
    'Meera Inimai': GOOGLE_FONT,
    'Megrim': GOOGLE_FONT,
    'Meie Script': GOOGLE_FONT,
    'Merienda': GOOGLE_FONT,
    'Merienda One': GOOGLE_FONT,
    'Merriweather': GOOGLE_FONT,
    'Merriweather Sans': GOOGLE_FONT,
    'Metal': GOOGLE_FONT,
    'Metal Mania': GOOGLE_FONT,
    'Metamorphous': GOOGLE_FONT,
    'Metrophobic': GOOGLE_FONT,
    'Michroma': GOOGLE_FONT,
    'Milonga': GOOGLE_FONT,
    'Miltonian': GOOGLE_FONT,
    'Miltonian Tattoo': GOOGLE_FONT,
    'Mina': GOOGLE_FONT,
    'Miniver': GOOGLE_FONT,
    'Miriam Libre': GOOGLE_FONT,
    'Mirza': GOOGLE_FONT,
    'Miss Fajardose': GOOGLE_FONT,
    'Mitr': GOOGLE_FONT,
    'Modak': GOOGLE_FONT,
    'Modern Antiqua': GOOGLE_FONT,
    'Mogra': GOOGLE_FONT,
    'Molengo': GOOGLE_FONT,
    'Molle': GOOGLE_FONT,
    'Monda': GOOGLE_FONT,
    'Monofett': GOOGLE_FONT,
    'Monoton': GOOGLE_FONT,
    'Monsieur La Doulaise': GOOGLE_FONT,
    'Montaga': GOOGLE_FONT,
    'Montez': GOOGLE_FONT,
    'Montserrat': GOOGLE_FONT,
    'Montserrat Alternates': GOOGLE_FONT,
    'Montserrat Subrayada': GOOGLE_FONT,
    'Moul': GOOGLE_FONT,
    'Moulpali': GOOGLE_FONT,
    'Mountains of Christmas': GOOGLE_FONT,
    'Mouse Memoirs': GOOGLE_FONT,
    'Mr Bedfort': GOOGLE_FONT,
    'Mr Dafoe': GOOGLE_FONT,
    'Mr De Haviland': GOOGLE_FONT,
    'Mrs Saint Delafield': GOOGLE_FONT,
    'Mrs Sheppards': GOOGLE_FONT,
    'Mukta': GOOGLE_FONT,
    'Mukta Mahee': GOOGLE_FONT,
    'Mukta Malar': GOOGLE_FONT,
    'Mukta Vaani': GOOGLE_FONT,
    'Muli': GOOGLE_FONT,
    'Mulish': GOOGLE_FONT,
    'MuseoModerno': GOOGLE_FONT,
    'Mystery Quest': GOOGLE_FONT,
    'NTR': GOOGLE_FONT,
    'Nanum Brush Script': GOOGLE_FONT,
    'Nanum Gothic': GOOGLE_FONT,
    'Nanum Gothic Coding': GOOGLE_FONT,
    'Nanum Myeongjo': GOOGLE_FONT,
    'Nanum Pen Script': GOOGLE_FONT,
    'Neucha': GOOGLE_FONT,
    'Neuton': GOOGLE_FONT,
    'New Rocker': GOOGLE_FONT,
    'News Cycle': GOOGLE_FONT,
    'Niconne': GOOGLE_FONT,
    'Niramit': GOOGLE_FONT,
    'Nixie One': GOOGLE_FONT,
    'Nobile': GOOGLE_FONT,
    'Nokora': GOOGLE_FONT,
    'Norican': GOOGLE_FONT,
    'Nosifer': GOOGLE_FONT,
    'Notable': GOOGLE_FONT,
    'Nothing You Could Do': GOOGLE_FONT,
    'Noticia Text': GOOGLE_FONT,
    'Noto Sans': GOOGLE_FONT,
    'Noto Sans HK': GOOGLE_FONT,
    'Noto Sans JP': GOOGLE_FONT,
    'Noto Sans KR': GOOGLE_FONT,
    'Noto Sans SC': GOOGLE_FONT,
    'Noto Sans TC': GOOGLE_FONT,
    'Noto Serif': GOOGLE_FONT,
    'Noto Serif JP': GOOGLE_FONT,
    'Noto Serif KR': GOOGLE_FONT,
    'Noto Serif SC': GOOGLE_FONT,
    'Noto Serif TC': GOOGLE_FONT,
    'Nova Cut': GOOGLE_FONT,
    'Nova Flat': GOOGLE_FONT,
    'Nova Mono': GOOGLE_FONT,
    'Nova Oval': GOOGLE_FONT,
    'Nova Round': GOOGLE_FONT,
    'Nova Script': GOOGLE_FONT,
    'Nova Slim': GOOGLE_FONT,
    'Nova Square': GOOGLE_FONT,
    'Numans': GOOGLE_FONT,
    'Nunito': GOOGLE_FONT,
    'Nunito Sans': GOOGLE_FONT,
    'Odibee Sans': GOOGLE_FONT,
    'Odor Mean Chey': GOOGLE_FONT,
    'Offside': GOOGLE_FONT,
    'Old Standard TT': GOOGLE_FONT,
    'Oldenburg': GOOGLE_FONT,
    'Oleo Script': GOOGLE_FONT,
    'Oleo Script Swash Caps': GOOGLE_FONT,
    'Open Sans': GOOGLE_FONT,
    'Open Sans Condensed': GOOGLE_FONT,
    'Oranienbaum': GOOGLE_FONT,
    'Orbitron': GOOGLE_FONT,
    'Oregano': GOOGLE_FONT,
    'Orienta': GOOGLE_FONT,
    'Original Surfer': GOOGLE_FONT,
    'Oswald': GOOGLE_FONT,
    'Over the Rainbow': GOOGLE_FONT,
    'Overlock': GOOGLE_FONT,
    'Overlock SC': GOOGLE_FONT,
    'Overpass': GOOGLE_FONT,
    'Overpass Mono': GOOGLE_FONT,
    'Ovo': GOOGLE_FONT,
    'Oxanium': GOOGLE_FONT,
    'Oxygen': GOOGLE_FONT,
    'Oxygen Mono': GOOGLE_FONT,
    'PT Mono': GOOGLE_FONT,
    'PT Sans': GOOGLE_FONT,
    'PT Sans Caption': GOOGLE_FONT,
    'PT Sans Narrow': GOOGLE_FONT,
    'PT Serif': GOOGLE_FONT,
    'PT Serif Caption': GOOGLE_FONT,
    'Pacifico': GOOGLE_FONT,
    'Padauk': GOOGLE_FONT,
    'Palanquin': GOOGLE_FONT,
    'Palanquin Dark': GOOGLE_FONT,
    'Pangolin': GOOGLE_FONT,
    'Paprika': GOOGLE_FONT,
    'Parisienne': GOOGLE_FONT,
    'Passero One': GOOGLE_FONT,
    'Passion One': GOOGLE_FONT,
    'Pathway Gothic One': GOOGLE_FONT,
    'Patrick Hand': GOOGLE_FONT,
    'Patrick Hand SC': GOOGLE_FONT,
    'Pattaya': GOOGLE_FONT,
    'Patua One': GOOGLE_FONT,
    'Pavanam': GOOGLE_FONT,
    'Paytone One': GOOGLE_FONT,
    'Peddana': GOOGLE_FONT,
    'Peralta': GOOGLE_FONT,
    'Permanent Marker': GOOGLE_FONT,
    'Petit Formal Script': GOOGLE_FONT,
    'Petrona': GOOGLE_FONT,
    'Philosopher': GOOGLE_FONT,
    'Piedra': GOOGLE_FONT,
    'Pinyon Script': GOOGLE_FONT,
    'Pirata One': GOOGLE_FONT,
    'Plaster': GOOGLE_FONT,
    'Play': GOOGLE_FONT,
    'Playball': GOOGLE_FONT,
    'Playfair Display': GOOGLE_FONT,
    'Playfair Display SC': GOOGLE_FONT,
    'Podkova': GOOGLE_FONT,
    'Poiret One': GOOGLE_FONT,
    'Poller One': GOOGLE_FONT,
    'Poly': GOOGLE_FONT,
    'Pompiere': GOOGLE_FONT,
    'Pontano Sans': GOOGLE_FONT,
    'Poor Story': GOOGLE_FONT,
    'Poppins': GOOGLE_FONT,
    'Port Lligat Sans': GOOGLE_FONT,
    'Port Lligat Slab': GOOGLE_FONT,
    'Pragati Narrow': GOOGLE_FONT,
    'Prata': GOOGLE_FONT,
    'Preahvihear': GOOGLE_FONT,
    'Press Start 2P': GOOGLE_FONT,
    'Pridi': GOOGLE_FONT,
    'Princess Sofia': GOOGLE_FONT,
    'Prociono': GOOGLE_FONT,
    'Prompt': GOOGLE_FONT,
    'Prosto One': GOOGLE_FONT,
    'Proza Libre': GOOGLE_FONT,
    'Public Sans': GOOGLE_FONT,
    'Puritan': GOOGLE_FONT,
    'Purple Purse': GOOGLE_FONT,
    'Quando': GOOGLE_FONT,
    'Quantico': GOOGLE_FONT,
    'Quattrocento': GOOGLE_FONT,
    'Quattrocento Sans': GOOGLE_FONT,
    'Questrial': GOOGLE_FONT,
    'Quicksand': GOOGLE_FONT,
    'Quintessential': GOOGLE_FONT,
    'Qwigley': GOOGLE_FONT,
    'Racing Sans One': GOOGLE_FONT,
    'Radley': GOOGLE_FONT,
    'Rajdhani': GOOGLE_FONT,
    'Rakkas': GOOGLE_FONT,
    'Raleway': GOOGLE_FONT,
    'Raleway Dots': GOOGLE_FONT,
    'Ramabhadra': GOOGLE_FONT,
    'Ramaraja': GOOGLE_FONT,
    'Rambla': GOOGLE_FONT,
    'Rammetto One': GOOGLE_FONT,
    'Ranchers': GOOGLE_FONT,
    'Rancho': GOOGLE_FONT,
    'Ranga': GOOGLE_FONT,
    'Rasa': GOOGLE_FONT,
    'Rationale': GOOGLE_FONT,
    'Ravi Prakash': GOOGLE_FONT,
    'Red Hat Display': GOOGLE_FONT,
    'Red Hat Text': GOOGLE_FONT,
    'Redressed': GOOGLE_FONT,
    'Reem Kufi': GOOGLE_FONT,
    'Reenie Beanie': GOOGLE_FONT,
    'Revalia': GOOGLE_FONT,
    'Rhodium Libre': GOOGLE_FONT,
    'Ribeye': GOOGLE_FONT,
    'Ribeye Marrow': GOOGLE_FONT,
    'Righteous': GOOGLE_FONT,
    'Risque': GOOGLE_FONT,
    'Roboto': GOOGLE_FONT,
    'Roboto Condensed': GOOGLE_FONT,
    'Roboto Mono': GOOGLE_FONT,
    'Roboto Slab': GOOGLE_FONT,
    'Rochester': GOOGLE_FONT,
    'Rock Salt': GOOGLE_FONT,
    'Rokkitt': GOOGLE_FONT,
    'Romanesco': GOOGLE_FONT,
    'Ropa Sans': GOOGLE_FONT,
    'Rosario': GOOGLE_FONT,
    'Rosarivo': GOOGLE_FONT,
    'Rouge Script': GOOGLE_FONT,
    'Rozha One': GOOGLE_FONT,
    'Rubik': GOOGLE_FONT,
    'Rubik Mono One': GOOGLE_FONT,
    'Ruda': GOOGLE_FONT,
    'Rufina': GOOGLE_FONT,
    'Ruge Boogie': GOOGLE_FONT,
    'Ruluko': GOOGLE_FONT,
    'Rum Raisin': GOOGLE_FONT,
    'Ruslan Display': GOOGLE_FONT,
    'Russo One': GOOGLE_FONT,
    'Ruthie': GOOGLE_FONT,
    'Rye': GOOGLE_FONT,
    'Sacramento': GOOGLE_FONT,
    'Sahitya': GOOGLE_FONT,
    'Sail': GOOGLE_FONT,
    'Saira': GOOGLE_FONT,
    'Saira Condensed': GOOGLE_FONT,
    'Saira Extra Condensed': GOOGLE_FONT,
    'Saira Semi Condensed': GOOGLE_FONT,
    'Saira Stencil One': GOOGLE_FONT,
    'Salsa': GOOGLE_FONT,
    'Sanchez': GOOGLE_FONT,
    'Sancreek': GOOGLE_FONT,
    'Sansita': GOOGLE_FONT,
    'Sarabun': GOOGLE_FONT,
    'Sarala': GOOGLE_FONT,
    'Sarina': GOOGLE_FONT,
    'Sarpanch': GOOGLE_FONT,
    'Satisfy': GOOGLE_FONT,
    'Sawarabi Gothic': GOOGLE_FONT,
    'Sawarabi Mincho': GOOGLE_FONT,
    'Scada': GOOGLE_FONT,
    'Scheherazade': GOOGLE_FONT,
    'Schoolbell': GOOGLE_FONT,
    'Scope One': GOOGLE_FONT,
    'Seaweed Script': GOOGLE_FONT,
    'Secular One': GOOGLE_FONT,
    'Sedgwick Ave': GOOGLE_FONT,
    'Sedgwick Ave Display': GOOGLE_FONT,
    'Sen': GOOGLE_FONT,
    'Sevillana': GOOGLE_FONT,
    'Seymour One': GOOGLE_FONT,
    'Shadows Into Light': GOOGLE_FONT,
    'Shadows Into Light Two': GOOGLE_FONT,
    'Shanti': GOOGLE_FONT,
    'Share': GOOGLE_FONT,
    'Share Tech': GOOGLE_FONT,
    'Share Tech Mono': GOOGLE_FONT,
    'Shojumaru': GOOGLE_FONT,
    'Short Stack': GOOGLE_FONT,
    'Shrikhand': GOOGLE_FONT,
    'Siemreap': GOOGLE_FONT,
    'Sigmar One': GOOGLE_FONT,
    'Signika': GOOGLE_FONT,
    'Signika Negative': GOOGLE_FONT,
    'Simonetta': GOOGLE_FONT,
    'Single Day': GOOGLE_FONT,
    'Sintony': GOOGLE_FONT,
    'Sirin Stencil': GOOGLE_FONT,
    'Six Caps': GOOGLE_FONT,
    'Skranji': GOOGLE_FONT,
    'Slabo 13px': GOOGLE_FONT,
    'Slabo 27px': GOOGLE_FONT,
    'Slackey': GOOGLE_FONT,
    'Smokum': GOOGLE_FONT,
    'Smythe': GOOGLE_FONT,
    'Sniglet': GOOGLE_FONT,
    'Snippet': GOOGLE_FONT,
    'Snowburst One': GOOGLE_FONT,
    'Sofadi One': GOOGLE_FONT,
    'Sofia': GOOGLE_FONT,
    'Solway': GOOGLE_FONT,
    'Song Myung': GOOGLE_FONT,
    'Sonsie One': GOOGLE_FONT,
    'Sorts Mill Goudy': GOOGLE_FONT,
    'Source Code Pro': GOOGLE_FONT,
    'Source Sans Pro': GOOGLE_FONT,
    'Source Serif Pro': GOOGLE_FONT,
    'Space Mono': GOOGLE_FONT,
    'Spartan': GOOGLE_FONT,
    'Special Elite': GOOGLE_FONT,
    'Spectral': GOOGLE_FONT,
    'Spectral SC': GOOGLE_FONT,
    'Spicy Rice': GOOGLE_FONT,
    'Spinnaker': GOOGLE_FONT,
    'Spirax': GOOGLE_FONT,
    'Squada One': GOOGLE_FONT,
    'Sree Krushnadevaraya': GOOGLE_FONT,
    'Sriracha': GOOGLE_FONT,
    'Srisakdi': GOOGLE_FONT,
    'Staatliches': GOOGLE_FONT,
    'Stalemate': GOOGLE_FONT,
    'Stalinist One': GOOGLE_FONT,
    'Stardos Stencil': GOOGLE_FONT,
    'Stint Ultra Condensed': GOOGLE_FONT,
    'Stint Ultra Expanded': GOOGLE_FONT,
    'Stoke': GOOGLE_FONT,
    'Strait': GOOGLE_FONT,
    'Stylish': GOOGLE_FONT,
    'Sue Ellen Francisco': GOOGLE_FONT,
    'Suez One': GOOGLE_FONT,
    'Sulphur Point': GOOGLE_FONT,
    'Sumana': GOOGLE_FONT,
    'Sunflower': GOOGLE_FONT,
    'Sunshiney': GOOGLE_FONT,
    'Supermercado One': GOOGLE_FONT,
    'Sura': GOOGLE_FONT,
    'Suranna': GOOGLE_FONT,
    'Suravaram': GOOGLE_FONT,
    'Suwannaphum': GOOGLE_FONT,
    'Swanky and Moo Moo': GOOGLE_FONT,
    'Syncopate': GOOGLE_FONT,
    'Tajawal': GOOGLE_FONT,
    'Tangerine': GOOGLE_FONT,
    'Taprom': GOOGLE_FONT,
    'Tauri': GOOGLE_FONT,
    'Taviraj': GOOGLE_FONT,
    'Teko': GOOGLE_FONT,
    'Telex': GOOGLE_FONT,
    'Tenali Ramakrishna': GOOGLE_FONT,
    'Tenor Sans': GOOGLE_FONT,
    'Text Me One': GOOGLE_FONT,
    'Thasadith': GOOGLE_FONT,
    'The Girl Next Door': GOOGLE_FONT,
    'Tienne': GOOGLE_FONT,
    'Tillana': GOOGLE_FONT,
    'Timmana': GOOGLE_FONT,
    'Tinos': GOOGLE_FONT,
    'Titan One': GOOGLE_FONT,
    'Titillium Web': GOOGLE_FONT,
    'Tomorrow': GOOGLE_FONT,
    'Trade Winds': GOOGLE_FONT,
    'Trirong': GOOGLE_FONT,
    'Trocchi': GOOGLE_FONT,
    'Trochut': GOOGLE_FONT,
    'Trykker': GOOGLE_FONT,
    'Tulpen One': GOOGLE_FONT,
    'Turret Road': GOOGLE_FONT,
    'Ubuntu': GOOGLE_FONT,
    'Ubuntu Condensed': GOOGLE_FONT,
    'Ubuntu Mono': GOOGLE_FONT,
    'Ultra': GOOGLE_FONT,
    'Uncial Antiqua': GOOGLE_FONT,
    'Underdog': GOOGLE_FONT,
    'Unica One': GOOGLE_FONT,
    'UnifrakturCook': GOOGLE_FONT,
    'UnifrakturMaguntia': GOOGLE_FONT,
    'Unkempt': GOOGLE_FONT,
    'Unlock': GOOGLE_FONT,
    'Unna': GOOGLE_FONT,
    'VT323': GOOGLE_FONT,
    'Vampiro One': GOOGLE_FONT,
    'Varela': GOOGLE_FONT,
    'Varela Round': GOOGLE_FONT,
    'Vast Shadow': GOOGLE_FONT,
    'Vesper Libre': GOOGLE_FONT,
    'Viaoda Libre': GOOGLE_FONT,
    'Vibes': GOOGLE_FONT,
    'Vibur': GOOGLE_FONT,
    'Victor Mono': GOOGLE_FONT,
    'Vidaloka': GOOGLE_FONT,
    'Viga': GOOGLE_FONT,
    'Voces': GOOGLE_FONT,
    'Volkhov': GOOGLE_FONT,
    'Vollkorn': GOOGLE_FONT,
    'Vollkorn SC': GOOGLE_FONT,
    'Voltaire': GOOGLE_FONT,
    'Waiting for the Sunrise': GOOGLE_FONT,
    'Wallpoet': GOOGLE_FONT,
    'Walter Turncoat': GOOGLE_FONT,
    'Warnes': GOOGLE_FONT,
    'Wellfleet': GOOGLE_FONT,
    'Wendy One': GOOGLE_FONT,
    'Wire One': GOOGLE_FONT,
    'Work Sans': GOOGLE_FONT,
    'Yanone Kaffeesatz': GOOGLE_FONT,
    'Yantramanav': GOOGLE_FONT,
    'Yatra One': GOOGLE_FONT,
    'Yellowtail': GOOGLE_FONT,
    'Yeon Sung': GOOGLE_FONT,
    'Yeseva One': GOOGLE_FONT,
    'Yesteryear': GOOGLE_FONT,
    'Yrsa': GOOGLE_FONT,
    'ZCOOL KuaiLe': GOOGLE_FONT,
    'ZCOOL QingKe HuangYou': GOOGLE_FONT,
    'ZCOOL XiaoWei': GOOGLE_FONT,
    'Zeyada': GOOGLE_FONT,
    'Zhi Mang Xing': GOOGLE_FONT,
    'Zilla Slab': GOOGLE_FONT,
    'Zilla Slab Highlight': GOOGLE_FONT,
  };
// </editor-fold>
