
 const CONSTANTS = {
  TEMPLATE_UPDATED: 'TEMPLATE_UPDATED',
  TEMPLATE_NEED_UPDATE: 'TEMPLATE_NEED_UPDATE',
  TEMPLATE_SAVING: 'TEMPLATE_SAVING',
  DEFAULT_BREAKPOINT: 'DEFAULT_BREAKPOINT',
};
 export default CONSTANTS;