// Automatically generated file with translations
// Do not edit manually!

export const translations: Record<string, Record<string, string>> = {
  "ru": {
    "add_new_expense_amount": "Enter amount",
    "add_new_expense_description": "Enter description",
    "ask_to_accountant": "Describe your question to the accountant.",
    "ask_to_client_account": "Enter client's bank account",
    "ask_to_client_address": "Enter client's address",
    "ask_to_client_name": "Enter client's name",
    "ask_to_client_pib": "Enter client's PIB",
    "ask_to_invoice_amount": "Enter invoice total amount in RSD",
    "ask_to_invoice_service_name": "Enter service name:",
    "ask_to_lawyer": "Describe your question to the lawyer.",
    "companyName": "Enter your company's full name.",
    "consultation_auto_answer": "Thank you! Your question has been sent.",
    "consultation_greeting": "Choose whom to contact.",
    "email": "Lastly, enter your email.",
    "help": "Available commands:\r\n/start - start\r\n/help - help",
    "invoice_auto_answer": "Invoice created successfully",
    "mainMenu": "Choose a menu section.",
    "mainService": "Enter your main service (e.g., 'Programming services'). We will use it as a base to quickly create invoices.",
    "okved": "Enter your activity code (OKVED).",
    "onboardingThanks": "Great, your profile is set up!\r\nYou can now use the main menu.\r\nYou can open the menu anytime with /menu",
    "phone": "Thank you. Now enter your contact phone.",
    "pib": "Enter your PIB (tax number).",
    "selectLanguage": "Choose language:",
    "select_profile_item": "Edit profile",
    "select_report": "Choose report",
    "select_template": "Choose template:",
    "show_client_card": "Client card",
    "template_auto_answer": "Generating template",
    "welcome": "Welcome to bznrs! Your digital assistant for flat-tax entrepreneurs. Let's set up your profile."
  },
  "sr": {
    "add_new_expense_amount": "Enter amount",
    "add_new_expense_description": "Enter description",
    "ask_to_accountant": "Describe your question to the accountant.",
    "ask_to_client_account": "Enter client's bank account",
    "ask_to_client_address": "Enter client's address",
    "ask_to_client_name": "Enter client's name",
    "ask_to_client_pib": "Enter client's PIB",
    "ask_to_invoice_amount": "Enter invoice total amount in RSD",
    "ask_to_invoice_service_name": "Enter service name:",
    "ask_to_lawyer": "Describe your question to the lawyer.",
    "companyName": "Enter your company's full name.",
    "consultation_auto_answer": "Thank you! Your question has been sent.",
    "consultation_greeting": "Choose whom to contact.",
    "email": "Lastly, enter your email.",
    "help": "Available commands:\r\n/start - start\r\n/help - help",
    "invoice_auto_answer": "Invoice created successfully",
    "mainMenu": "Choose a menu section.",
    "mainService": "Enter your main service (e.g., 'Programming services'). We will use it as a base to quickly create invoices.",
    "okved": "Enter your activity code (OKVED).",
    "onboardingThanks": "Great, your profile is set up!\r\nYou can now use the main menu.\r\nYou can open the menu anytime with /menu",
    "phone": "Thank you. Now enter your contact phone.",
    "pib": "Enter your PIB (tax number).",
    "selectLanguage": "Choose language:",
    "select_profile_item": "Edit profile",
    "select_report": "Choose report",
    "select_template": "Choose template:",
    "show_client_card": "Client card",
    "template_auto_answer": "Generating template",
    "welcome": "Welcome to bznrs! Your digital assistant for flat-tax entrepreneurs. Let's set up your profile."
  }
};
