// Automatically generated file with translations
// Do not edit manually!

export const translations: Record<string, Record<string, string>> = {
  "ru": {
    "add_new_expense_amount": "Enter amount",
    "add_new_expense_description": "Enter description",
    "ask_to_accountant": "Describe your question to the accountant.",
    "ask_to_client_account": "Enter client account number",
    "ask_to_client_address": "Enter client address",
    "ask_to_client_name": "Enter client name",
    "ask_to_client_pib": "Enter client PIB",
    "ask_to_invoice_amount": "Enter total invoice amount in RSD",
    "ask_to_invoice_service_name": "Enter service name:",
    "ask_to_lawyer": "Describe your question to the lawyer.",
    "companyName": "Enter the full name of your company.",
    "consultation_auto_answer": "Thank you! Your question has been sent successfully.",
    "consultation_greeting": "Choose who to contact.",
    "email": "And finally, enter your email.",
    "help": "Available commands:\r\n/start - start working\r\n/help - help",
    "invoice_auto_answer": "Invoice created successfully",
    "mainMenu": "Choose a menu section.",
    "mainService": "Enter your main service (e.g., 'Programming services'). We will use it as a basis for quick invoice creation.",
    "okved": "Enter your activity code (OKVED).",
    "onboardingThanks": "Great, your profile is set up!\r\nNow you can use the main menu.\r\nYou can also open the menu at any time with the /menu command",
    "phone": "Thank you. Now enter your contact phone number.",
    "pib": "Enter your PIB (tax number).",
    "selectLanguage": "Izaberite jezik / Choose language:",
    "select_profile_item": "Profile editing",
    "select_report": "Choose report",
    "select_template": "Choose template:",
    "show_client_card": "Client card",
    "template_auto_answer": "Generating template",
    "welcome": "Welcome to bznrs! Your digital assistant for freelancers. Let's set up your profile."
  },
  "sr": {
    "add_new_expense_amount": "Enter amount",
    "add_new_expense_description": "Enter description",
    "ask_to_accountant": "Describe your question to the accountant.",
    "ask_to_client_account": "Enter client account number",
    "ask_to_client_address": "Enter client address",
    "ask_to_client_name": "Enter client name",
    "ask_to_client_pib": "Enter client PIB",
    "ask_to_invoice_amount": "Enter total invoice amount in RSD",
    "ask_to_invoice_service_name": "Enter service name:",
    "ask_to_lawyer": "Describe your question to the lawyer.",
    "companyName": "Enter the full name of your company.",
    "consultation_auto_answer": "Thank you! Your question has been sent successfully.",
    "consultation_greeting": "Choose who to contact.",
    "email": "And finally, enter your email.",
    "help": "Available commands:\r\n/start - start working\r\n/help - help",
    "invoice_auto_answer": "Invoice created successfully",
    "mainMenu": "Choose a menu section.",
    "mainService": "Enter your main service (e.g., 'Programming services'). We will use it as a basis for quick invoice creation.",
    "okved": "Enter your activity code (OKVED).",
    "onboardingThanks": "Great, your profile is set up!\r\nNow you can use the main menu.\r\nYou can also open the menu at any time with the /menu command",
    "phone": "Thank you. Now enter your contact phone number.",
    "pib": "Enter your PIB (tax number).",
    "selectLanguage": "Izaberite jezik / Choose language:",
    "select_profile_item": "Profile editing",
    "select_report": "Choose report",
    "select_template": "Choose template:",
    "show_client_card": "Client card",
    "template_auto_answer": "Generating template",
    "welcome": "Welcome to bznrs! Your digital assistant for freelancers. Let's set up your profile."
  }
};
