const LANG_OPTIONS = [
  { value: "aa", title: "Afaraf", label: "Afar", direction: "ltr" },
  { value: "ab", title: "Аҧсуа", label: "Abkhaz", direction: "ltr" },
  { value: "ad", title: "Адыгабзэ", label: "Adyghe", direction: "ltr" },
  { value: "ae", title: "Avesta", label: "Avestan", direction: "ltr" },
  { value: "af", title: "Afrikaans", label: "Afrikaans", direction: "ltr" },
  { value: "ak", title: "Akan", label: "Akan", direction: "ltr" },
  { value: "al", title: "алтайдыҥ тилин", label: "Altai", direction: "ltr" },
  { value: "am", title: "አማርኛ", label: "Amharic", direction: "ltr" },
  { value: "an", title: "Aragonés", label: "Aragonese", direction: "ltr" },
  { value: "ao", title: "廈門話 ", label: "Amoy", direction: "ltr" },
  { value: "ar", title: "العربية", label: "Arabic", direction: "ltr" },
  { value: "as", title: "অসমীয়া", label: "Assamese", direction: "ltr" },
  { value: "at", title: "абаза бызшва", label: "Abaza", direction: "ltr" },
  { value: "av", title: "авар мацӀ", label: "Avaric", direction: "ltr" },
  { value: "ay", title: "aymar aru", label: "Aymara", direction: "ltr" },
  { value: "az", title: "azərbaycan dili", label: "Azerbaijani", direction: "ltr" },
  { value: "ba", title: "башҡорт теле", label: "Bashkir", direction: "ltr" },
  { value: "be", title: "беларуская мова", label: "Belarusian", direction: "ltr" },
  { value: "bg", title: "български език", label: "Bulgarian", direction: "ltr" },
  { value: "bh", title: "भोजपुरी", label: "Bihari", direction: "ltr" },
  { value: "bi", title: "Bislama", label: "Bislama", direction: "ltr" },
  { value: "bk", title: "Bikol Naga", label: "Bikol", direction: "ltr" },
  { value: "bm", title: "bamanankan", label: "Bambara", direction: "ltr" },
  { value: "bn", title: "বাংলা", label: "Bengali", direction: "ltr" },
  { value: "bo", title: "བོད་ཡིག", label: "Tibetan", direction: "ltr" },
  { value: "br", title: "brezhoneg", label: "Breton", direction: "ltr" },
  { value: "bs", title: "bosanski jezik", label: "Bosnian", direction: "ltr" },
  { value: "bu", title: "буряад хэлэн", label: "Buryat", direction: "ltr" },
  { value: "ca", title: "català", label: "Catalan", direction: "ltr" },
  { value: "ce", title: "Нохчийн мотт", label: "Chechen", direction: "ltr" },
  { value: "ch", title: "Chamoru", label: "Chamorro", direction: "ltr" },
  { value: "ck", title: "Chuuk", label: "Chuukese", direction: "ltr" },
  { value: "cn", title: "廣東話", label: "Cantonese", direction: "ltr" },
  { value: "co", title: "corsu", label: "Corsican", direction: "ltr" },
  { value: "cr", title: "ᓀᐦᐃᔭᐍᐏᐣ", label: "Cree", direction: "ltr" },
  { value: "cs", title: "čeština", label: "Czech", direction: "ltr" },
  { value: "ct", title: "къырымтатар тили", label: "Crimean Tatar", direction: "ltr" },
  { value: "cu", title: "словѣньскъ", label: "Church Slavic", direction: "ltr" },
  { value: "cv", title: "Çăvaşla", label: "Chuvash", direction: "ltr" },
  { value: "cy", title: "Cymraeg", label: "Welsh", direction: "ltr" },
  { value: "da", title: "dansk", label: "Danish", direction: "ltr" },
  { value: "de", title: "Deutsch", label: "German", direction: "ltr" },
  { value: "dp", title: "Dari", label: "Dari Persian", direction: "ltr" },
  { value: "dv", title: "ދިވެހި", label: "Divehi", direction: "ltr" },
  { value: "dz", title: "རྫོང་ཁ", label: "Dzongkha", direction: "ltr" },
  { value: "ee", title: "Eʋegbe", label: "Ewe", direction: "ltr" },
  { value: "el", title: "Ελληνικά", label: "Greek", direction: "ltr" },
  { value: "en", title: "English", label: "English", direction: "ltr" },
  { value: "eo", title: "Esperanto", label: "Esperanto", direction: "ltr" },
  { value: "er", title: "эрзянь кель", label: "Erzya", direction: "ltr" },
  { value: "es", title: "Español", label: "Spanish", direction: "ltr" },
  { value: "et", title: "eesti", label: "Estonian", direction: "ltr" },
  { value: "eu", title: "euskara", label: "Basque", direction: "ltr" },
  { value: "fa", title: "فارسی", label: "Persian", direction: "ltr" },
  { value: "ff", title: "Fulfulde", label: "Fula", direction: "ltr" },
  { value: "fi", title: "suomi", label: "Finnish", direction: "ltr" },
  { value: "fj", title: "Na Vosa Vakaviti", label: "Fijian", direction: "ltr" },
  { value: "fo", title: "føroyskt", label: "Faroese", direction: "ltr" },
  { value: "fr", title: "français", label: "French", direction: "ltr" },
  { value: "fy", title: "Frysk", label: "Frisian", direction: "ltr" },
  { value: "ga", title: "Gaeilge", label: "Irish", direction: "ltr" },
  { value: "gd", title: "Gàidhlig", label: "Scottish Gaelic", direction: "ltr" },
  { value: "gl", title: "galego", label: "Galician", direction: "ltr" },
  { value: "gn", title: "Avañe'ẽ", label: "Guarani", direction: "ltr" },
  { value: "gu", title: "ગુજરાતી", label: "Gujarati", direction: "ltr" },
  { value: "gv", title: "Gaelg", label: "Manx", direction: "ltr" },
  { value: "ha", title: "Hausa", label: "Hausa", direction: "ltr" },
  { value: "he", title: "עברית", label: "Hebrew", direction: "ltr" },
  { value: "hh", title: "Хакас тілі", label: "Khakas", direction: "ltr" },
  { value: "hi", title: "हिन्दी", label: "Hindi", direction: "ltr" },
  { value: "ho", title: "Hiri Motu", label: "Hiri Motu", direction: "ltr" },
  { value: "hr", title: "hrvatski jezik", label: "Croatian", direction: "ltr" },
  { value: "ht", title: "Kreyòl ayisyen", label: "Haitian Creole", direction: "ltr" },
  { value: "hu", title: "Magyar", label: "Hungarian", direction: "ltr" },
  { value: "hy", title: "Հայերեն", label: "Armenian", direction: "ltr" },
  { value: "hz", title: "Otjiherero", label: "Herero", direction: "ltr" },
  { value: "ia", title: "Interlingua", label: "Interlingua", direction: "ltr" },
  { value: "id", title: "Bahasa Indonesia", label: "Indonesian", direction: "ltr" },
  { value: "ie", title: "Interlingue", label: "Interlingue", direction: "ltr" },
  { value: "ig", title: "Asụsụ Igbo", label: "Igbo", direction: "ltr" },
  { value: "ii", title: "ꆈꌠꁱꂷ", label: "Sichuan Yi", direction: "ltr" },
  { value: "ik", title: "Iñupiaq", label: "Inupiaq", direction: "ltr" },
  { value: "im", title: "勉語", label: "Iu Mien", direction: "ltr" },
  { value: "in", title: "гӏалгӏай мотт", label: "Ingush", direction: "ltr" },
  { value: "io", title: "Ido", label: "Ido", direction: "ltr" },
  { value: "is", title: "Íslenska", label: "Icelandic", direction: "ltr" },
  { value: "it", title: "Italiano", label: "Italian", direction: "ltr" },
  { value: "iu", title: "ᐃᓄᒃᑎᑐᑦ", label: "Inuktitut", direction: "ltr" },
  { value: "ix", title: "Interslavik", label: "Interslavik", direction: "ltr" },
  { value: "ja", title: "日本語", label: "Japanese", direction: "ltr" },
  { value: "ji", title: "Jieng", label: "Dinka", direction: "ltr" },
  { value: "jv", title: "Basa Jawa", label: "Javanese", direction: "ltr" },
  { value: "jw", title: "Jawi", label: "Cham", direction: "ltr" },
  { value: "ka", title: "ქართული", label: "Georgian", direction: "ltr" },
  { value: "kb", title: "адыгэбзэ", label: "Kabardian", direction: "ltr" },
  { value: "kc", title: "Къарачай-Малкъар тил", label: "Karachay-Balkar", direction: "ltr" },
  { value: "kg", title: "Kikongo", label: "Kongo", direction: "ltr" },
  { value: "kh", title: "ກຶມຫມຸ", label: "Khmu", direction: "ltr" },
  { value: "ki", title: "Gĩkũyũ", label: "Kikuyu", direction: "ltr" },
  { value: "kj", title: "Kwanyama", label: "Kuanyama", direction: "ltr" },
  { value: "kk", title: "Қазақ тілі", label: "Kazakh", direction: "ltr" },
  { value: "kl", title: "kalaallisut", label: "Greenlandic", direction: "ltr" },
  { value: "km", title: "ភាសាខ្មែរ", label: "Khmer", direction: "ltr" },
  { value: "kn", title: "ಕನ್ನಡ", label: "Kannada", direction: "ltr" },
  { value: "ko", title: "한국어", label: "Korean", direction: "ltr" },
  { value: "kp", title: "Хальмг келн", label: "Kalmyk", direction: "ltr" },
  { value: "kr", title: "Kanuri", label: "Kanuri", direction: "ltr" },
  { value: "ks", title: "कश्मीरी", label: "Kashmiri", direction: "ltr" },
  { value: "ku", title: "Kurdî", label: "Kurdish", direction: "ltr" },
  { value: "kv", title: "коми кыв", label: "Komi", direction: "ltr" },
  { value: "kw", title: "Kernewek", label: "Cornish", direction: "ltr" },
  { value: "ky", title: "Кыргызча", label: "Kyrgyz", direction: "ltr" },
  { value: "la", title: "Latine", label: "Latin", direction: "ltr" },
  { value: "lb", title: "Lëtzebuergesch", label: "Luxembourgish", direction: "ltr" },
  { value: "lg", title: "Luganda", label: "Ganda", direction: "ltr" },
  { value: "li", title: "Limburgs", label: "Limburgish", direction: "ltr" },
  { value: "ln", title: "Lingála", label: "Lingala", direction: "ltr" },
  { value: "lo", title: "ພາສາລາວ", label: "Lao", direction: "ltr" },
  { value: "lt", title: "lietuvių kalba", label: "Lithuanian", direction: "ltr" },
  { value: "lu", title: "Tshiluba", label: "Luba-Katanga", direction: "ltr" },
  { value: "lv", title: "latviešu valoda", label: "Latvian", direction: "ltr" },
  { value: "mc", title: "官话", label: "Mandarin", direction: "ltr" },
  { value: "md", title: "Mandinka", label: "Mandingo", direction: "ltr" },
  { value: "mg", title: "Malagasy fiteny", label: "Malagasy", direction: "ltr" },
  { value: "mh", title: "Kajin M̧ajeļ", label: "Marshallese", direction: "ltr" },
  { value: "mi", title: "te reo Māori", label: "Maori", direction: "ltr" },
  { value: "mk", title: "македонски јазик", label: "Macedonian", direction: "ltr" },
  { value: "ml", title: "മലയാളം", label: "Malayalam", direction: "ltr" },
  { value: "mn", title: "Монгол хэл", label: "Mongolian", direction: "ltr" },
  { value: "mo", title: "мокшень кяль", label: "Moksha", direction: "ltr" },
  { value: "mr", title: "मराठी", label: "Marathi", direction: "ltr" },
  { value: "ms", title: "بهاس ملايو", label: "Malay", direction: "ltr" },
  { value: "mt", title: "Malti", label: "Maltese", direction: "ltr" },
  { value: "mu", title: "марий йылме", label: "Mari", direction: "ltr" },
  { value: "my", title: "ဗမာစာ", label: "Burmese", direction: "ltr" },
  { value: "na", title: "Ekakairũ Naoero", label: "Nauru", direction: "ltr" },
  { value: "nb", title: "Norsk bokmål", label: "Norwegian Bokmål", direction: "ltr" },
  { value: "nd", title: "isiNdebele", label: "Northern Ndebele", direction: "ltr" },
  { value: "ne", title: "नेपाली", label: "Nepali", direction: "ltr" },
  { value: "ng", title: "Owambo", label: "Ndonga", direction: "ltr" },
  { value: "ni", title: "ногайша", label: "Nogai", direction: "ltr" },
  { value: "nl", title: "Nederlands", label: "Dutch", direction: "ltr" },
  { value: "nn", title: "Norsk nynorsk", label: "Norwegian Nynorsk", direction: "ltr" },
  { value: "no", title: "Norsk", label: "Norwegian", direction: "ltr" },
  { value: "nr", title: "isiNdebele", label: "Southern Ndebele", direction: "ltr" },
  { value: "nv", title: "Diné bizaad", label: "Navajo", direction: "ltr" },
  { value: "ny", title: "chiCheŵa", label: "Chichewa", direction: "ltr" },
  { value: "oc", title: "occitan", label: "Occitan", direction: "ltr" },
  { value: "oj", title: "ᐊᓂᔑᓈᐯᒧᐎᓐ", label: "Ojibwa", direction: "ltr" },
  { value: "om", title: "Afaan Oromoo", label: "Oromo", direction: "ltr" },
  { value: "or", title: "ଓଡ଼ିଆ", label: "Oriya", direction: "ltr" },
  { value: "os", title: "ирон æвзаг", label: "Ossetian", direction: "ltr" },
  { value: "pa", title: "ਪੰਜਾਬੀ", label: "Punjabi", direction: "ltr" },
  { value: "ph", title: "Filipino", label: "Filipino", direction: "ltr" },
  { value: "pi", title: "पालि", label: "Pali", direction: "ltr" },
  { value: "pl", title: "Polski", label: "Polish", direction: "ltr" },
  { value: "ps", title: "پښتو", label: "Pashto", direction: "ltr" },
  { value: "pt", title: "Português", label: "Portuguese", direction: "ltr" },
  { value: "qu", title: "Runa Simi", label: "Quechua", direction: "ltr" },
  { value: "rm", title: "rumantsch grischun", label: "Romansh", direction: "ltr" },
  { value: "rn", title: "Ikirundi", label: "Kirundi", direction: "ltr" },
  { value: "ro", title: "limba română", label: "Romanian", direction: "ltr" },
  { value: "ru", title: "Русский", label: "Russian", direction: "ltr" },
  { value: "rw", title: "Kinyarwanda", label: "Kinyarwanda", direction: "ltr" },
  { value: "sa", title: "संस्कृतम्", label: "Sanskrit", direction: "ltr" },
  { value: "sc", title: "sardu", label: "Sardinian", direction: "ltr" },
  { value: "sd", title: "सिन्धी", label: "Sindhi", direction: "ltr" },
  { value: "se", title: "Davvisámegiella", label: "Northern Sami", direction: "ltr" },
  { value: "sg", title: "yângâ tî sängö", label: "Sango", direction: "ltr" },
  { value: "sh", title: "शेर्वी तम्ङे", label: "Sherpa", direction: "ltr" },
  { value: "si", title: "සිංහල", label: "Sinhala", direction: "ltr" },
  { value: "sk", title: "slovenčina", label: "Slovak", direction: "ltr" },
  { value: "sl", title: "slovenščina", label: "Slovenian", direction: "ltr" },
  { value: "sm", title: "gagana fa'a Samoa", label: "Samoan", direction: "ltr" },
  { value: "sn", title: "chiShona", label: "Shona", direction: "ltr" },
  { value: "so", title: "Soomaaliga", label: "Somali", direction: "ltr" },
  { value: "sq", title: "Shqip", label: "Albanian", direction: "ltr" },
  { value: "sr", title: "српски језик", label: "Serbian", direction: "ltr" },
  { value: "ss", title: "SiSwati", label: "Swati", direction: "ltr" },
  { value: "st", title: "Sesotho", label: "Southern Sotho", direction: "ltr" },
  { value: "su", title: "Basa Sunda", label: "Sundanese", direction: "ltr" },
  { value: "sv", title: "svenska", label: "Swedish", direction: "ltr" },
  { value: "sw", title: "Kiswahili", label: "Swahili", direction: "ltr" },
  { value: "ta", title: "தமிழ்", label: "Tamil", direction: "ltr" },
  { value: "te", title: "తెలుగు", label: "Telugu", direction: "ltr" },
  { value: "tg", title: "тоҷикӣ", label: "Tajik", direction: "ltr" },
  { value: "th", title: "ไทย", label: "Thai", direction: "ltr" },
  { value: "ti", title: "ትግርኛ", label: "Tigrinya", direction: "ltr" },
  { value: "tk", title: "Türkmen", label: "Turkmen", direction: "ltr" },
  { value: "tl", title: "Wikang Tagalog", label: "Tagalog", direction: "ltr" },
  { value: "tn", title: "Setswana", label: "Tswana", direction: "ltr" },
  { value: "to", title: "faka Tonga", label: "Tonga", direction: "ltr" },
  { value: "tp", title: "Thok Naath", label: "Nuer", direction: "ltr" },
  { value: "tr", title: "Türkçe", label: "Turkish", direction: "ltr" },
  { value: "ts", title: "Xitsonga", label: "Tsonga", direction: "ltr" },
  { value: "tt", title: "татарча", label: "Tatar", direction: "ltr" },
  { value: "tv", title: "Тыва дыл", label: "Tuvan", direction: "ltr" },
  { value: "tw", title: "Twi", label: "Twi", direction: "ltr" },
  { value: "ty", title: "Reo Tahiti", label: "Tahitian", direction: "ltr" },
  { value: "ud", title: "Удмурт кыл", label: "Udmurt", direction: "ltr" },
  { value: "ug", title: "ئۇيغۇرچە", label: "Uyghur", direction: "ltr" },
  { value: "uk", title: "українська мова", label: "Ukrainian", direction: "ltr" },
  { value: "ur", title: "اردو", label: "Urdu", direction: "ltr" },
  { value: "uz", title: "zbek", label: "Uzbek", direction: "ltr" },
  { value: "ve", title: "Tshivenḓa", label: "Venda", direction: "ltr" },
  { value: "vi", title: "Tiếng Việt", label: "Vietnamese", direction: "ltr" },
  { value: "vl", title: "Vlaams", label: "Flemish", direction: "ltr" },
  { value: "vo", title: "Volapük", label: "Volapük", direction: "ltr" },
  { value: "wa", title: "Walon", label: "Walloon", direction: "ltr" },
  { value: "wo", title: "Wollof", label: "Wolof", direction: "ltr" },
  { value: "xh", title: "isiXhosa", label: "Xhosa", direction: "ltr" },
  { value: "ya", title: "Саха тыла", label: "Yakut", direction: "ltr" },
  { value: "yi", title: "ייִדיש", label: "Yiddish", direction: "ltr" },
  { value: "yo", title: "Yorùbá", label: "Yoruba", direction: "ltr" },
  { value: "za", title: "Cuengh", label: "Zhuang", direction: "ltr" },
  { value: "zh", title: "中文", label: "Chinese", direction: "ltr" },
  { value: "zu", title: "isiZulu", label: "Zulu", direction: "ltr" }
]

export default LANG_OPTIONS
