export const SELECT_SECTION = "SECTION/SELECT_SECTION";
export const ADD_SECTION = "SECTION/CREATE_SECTION";
export const CHANGE_SECTION = "SECTION/CHANGE_SECTION";
export const REMOVE_SECTION = "SECTION/REMOVE_SECTION";
export const SELECT_WIDGET = "SECTION/SELECT_WIDGET";
export const ADD_WIDGET = "SECTION/ADD_WIDGET";
export const CHANGE_WIDGET = "SECTION/CHANGE_WIDGET";
export const REMOVE_WIDGET = "SECTION/REMOVE_WIDGET";
export const ADD_COLUMNS = "SECTION/ADD_COLUMNS";
export const REMOVE_COLUMNS = "SECTION/REMOVE_COLUMNS";
export const CHANGE_COLUMNS = "SECTION/CHANGE_COLUMNS";
export const IMPORT_STRUCTURE = "SECTION/IMPORT_STRUCTURE";

export const CHANGE_SETTINGS = "SETTINGS/CHANGE_SETTINGS";

export const MENU_DELETE_WIDGET = "MENU/DELETE_WIDGET";
export const MENU_CUT_WIDGET = "MENU/CUT_WIDGET";
export const MENU_COPY_WIDGET = "MENU/COPY_WIDGET";
export const MENU_PASTE_WIDGET = "MENU/PASTE_WIDGET";
export const MENU_PASTE_WIDGET_BEFORE = "MENU/PASTE_WIDGET_BEFORE";
export const MENU_PASTE_WIDGET_AFTER = "MENU/PASTE_WIDGET_AFTER";

export const MENU_COPY_STYLES = "MENU/COPY_STYLES";
export const MENU_PASTE_STYLES = "MENU/PASTE_STYLES";

export const MENU_DELETE_SECTION = "MENU/DELETE_SECTION";

export const LOADER = "APP/LOADER";
export const SHOW_ALERT = "APP/SHOW_ALERT";
export const HIDE_ALERT = "APP/HIDE_ALERT";
export const SHOW_WIDGETS = "APP/SHOW_WIDGETS";
export const HIDE_WIDGETS = "APP/HIDE_WIDGETS";

export const SWITCH_SETTINGS_TAB = "APP/SWITCH_SETTINGS_TAB";
