name = "altrp-bot-dev"
main = "src/worker/worker.ts"
compatibility_date = "2024-01-01"
workers_dev = true
account_id = "7f412ebe1901fb520bca3fbe424faf94"

[observability.logs]
enabled = true

# Environment variables
[vars]
NODE_ENV = "production"
LOCALE = "ru"

# KV Namespace для кэширования
[[kv_namespaces]]
binding = "BOT_KV"
id = "d823c3325ed84a5d8028ae15eace5967"
preview_id = "8d8585216d734945839f0836a7059340"

# D1 Database
# [[d1_databases]]
# binding = "DB"
# database_name = "altrp-bot-dev-db"
# database_id = "0b1f2889-cdfa-4f81-9454-22380d41b4da"

[[d1_databases]]
binding = "DB"
database_name = "consultant-bot-db"
database_id = "fa51d644-4e01-49ea-a661-0c74f8c986cc"

# R2 Storage
[[r2_buckets]]
binding = "BOT_STORAGE"
bucket_name = "altrp-bot-dev-storage"

# Cron triggers
[triggers]
crons = ["* * * * *"]

# Development configuration
# Для разработки и тестирования
[env.development]
name = "YOUR_WORKER_NAME-dev"

# Production configuration  
# Для продакшена
[env.production]
name = "YOUR_WORKER_NAME-prod"
