name = "altrp-app"
compatibility_date = "2025-10-13"
compatibility_flags = ["nodejs_compat"]
 main = "./woker.ts"

# D1 Database binding
[[d1_databases]]
binding = "D1"
database_name = "altrp-app-db"
database_id = "7254b146-5242-4957-8656-e1f176855ee8" # Will be filled after creating database

# Environment variables
[vars]
PAYLOAD_SECRET = "your-payload-secret-here"
NEXT_PUBLIC_SERVER_URL = "https://your-app-domain.com"
CRON_SECRET = "your-cron-secret-here"
PREVIEW_SECRET = "your-preview-secret-here"

